export const GEOPIFY_API_KEY = process.env.REACT_APP_GEOPIFY_API_KEY
export const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY
export const WEATHER_BIT_API_KEY = process.env.REACT_APP_WEATHER_BIT_API_KEY
export const GEOLOCATION_TOKEN_PARAM = process.env.REACT_APP_GEOLOCATION_TOKEN_PARAM
export const OPEN_WEATHER_MAP_API_KEY = process.env.REACT_APP_OPEN_WEATHER_MAP_API_KEY
